<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Concesionario [
<!ELEMENT Concesionario (coche*)>
<!ELEMENT coche (codigo, marca, modelo, matricula, potencia, plazas,
numPuertas )>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numPuertas (#PCDATA)>
]>
<Concesionario>
<coche>
    <codigo>10</codigo>
    <marca>AUDI</marca>
    <modelo>LQ3</modelo>
    <matricula>7463 BDH</matricula>
    <potencia>150CV</potencia>
    <plazas>5</plazas>
    <numPuertas>6</numPuertas>
</coche>
<coche>
    <codigo>25</codigo>
    <marca>SEAT</marca>
    <modelo>Leon</modelo>
    <matricula>8236 JDY</matricula>
    <potencia>120CV</potencia>
    <plazas>5</plazas>
    <numPuertas>6</numPuertas>
</coche>
<coche>
    <codigo>46</codigo>
    <marca>FORD</marca>
    <modelo>Mondeo</modelo>
    <matricula>7382 HST</matricula>
    <potencia>95CV</potencia>
    <plazas>4</plazas>
    <numPuertas>3</numPuertas>
</coche>
</Concesionario>