=== mariomateos16/XMLRepo/XML Repo/Clientes/Clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT clientes (sede)*>
<!ELEMENT sede (direccion|empleado|fecha|descripcion|cliente)*>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cliente (num_viviendas|coste_viviendas|res_viviendas|plazo)*>
<!ATTLIST cliente codigo CDATA #REQUIRED>
<!ELEMENT num_viviendas (#PCDATA)>
<!ELEMENT coste_viviendas (#PCDATA)>
<!ELEMENT res_viviendas (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== mariomateos16/XMLRepo/XML Repo/Clientes/Clientes.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A6476244">
        <direccion></direccion>
        <empleado></empleado>
        <fecha></fecha>
        <descripcion></descripcion>
        <cliente codigo="MMM-576">
            <num_viviendas></num_viviendas>
            <coste_viviendas></coste_viviendas>
            <res_viviendas></res_viviendas>
            <plazo></plazo>
        </cliente>
    </sede>
</clientes>
